export const TEXT = {
  COMMON: {
    LOADING: 'Loading...',
    ERROR: 'Something went wrong. Please try again.',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    DELETE: 'Delete',
    EDIT: 'Edit',
    VIEW: 'View',
    SEARCH: 'Search',
    FILTER: 'Filter',
    CLEAR: 'Clear',
    APPLY: 'Apply',
    SUBMIT: 'Submit',
    BACK: 'Back',
    NEXT: 'Next',
    PREVIOUS: 'Previous',
    CLOSE: 'Close',
    CONFIRM: 'Confirm',
    YES: 'Yes',
    NO: 'No',
    OR: 'or',
    AND: 'and',
    FROM: 'From',
    TO: 'To',
    ALL: 'All',
    NONE: 'None',
    PER_HOUR: '/hr',
    PER_SERVICE: '/service',
    REVIEWS: 'reviews',
    RATING: 'Rating',
    LOCATION: 'Location',
    AVAILABILITY: 'Availability',
    EXPERIENCE: 'Experience',
    YEARS: 'years',
    VIEW_ALL: 'View All',
    LEARN_MORE: 'Learn More',
    GET_STARTED: 'Get Started',
    BOOK_NOW: 'Book Now',
    SEND_MESSAGE: 'Send Message',
    SEND_ENQUIRY: 'Send Enquiry',
    ADD_TO_FAVORITES: 'Add to Favorites',
    REMOVE_FROM_FAVORITES: 'Remove from Favorites',
    NO_RESULTS: 'No results found',
    TRY_AGAIN: 'Try adjusting your filters or search terms.',
    PAGE: 'Page',
    OF: 'of',
    SHOWING: 'Showing',
    RESULTS: 'results',
    GRID_VIEW: 'Grid view',
    LIST_VIEW: 'List view',
    SORT_BY: 'Sort by',
    NEWEST: 'Newest',
    OLDEST: 'Oldest',
    PRICE_LOW: 'Price: Low to High',
    PRICE_HIGH: 'Price: High to Low',
    TOP_RATED: 'Top Rated',
    DEMO_MODE: 'Demo Mode — All data is simulated',
  },

  NAV: {
    HOME: 'Home',
    SEARCH: 'Find Cleaners',
    HOW_IT_WORKS: 'How It Works',
    ABOUT: 'About',
    LOGIN: 'Log In',
    REGISTER: 'Sign Up',
    DASHBOARD: 'Dashboard',
    LOGOUT: 'Log Out',
    BECOME_CLEANER: 'Become a Cleaner',
    CUSTOMER_DASHBOARD: 'My Dashboard',
    CLEANER_DASHBOARD: 'Cleaner Dashboard',
    ADMIN_DASHBOARD: 'Admin Panel',
    ENQUIRIES: 'Enquiries',
    MESSAGES: 'Messages',
    FAVORITES: 'Favorites',
    PROFILE: 'Profile',
    MY_SERVICES: 'My Services',
    BUSINESS_PROFILE: 'Business Profile',
    REVIEWS: 'Reviews',
    USERS: 'Users',
    SERVICES: 'Services',
    REPORTS: 'Reports',
  },

  HOME: {
    HERO_TITLE: 'Find Trusted Cleaners Near You',
    HERO_SUBTITLE: 'Connect with professional cleaners and cleaning businesses across Canada. Book residential, commercial, and specialized cleaning services with confidence.',
    SEARCH_PLACEHOLDER: 'Search for cleaning services, cleaners, or locations...',
    SEARCH_BUTTON: 'Search',
    POPULAR_CATEGORIES: 'Popular Categories',
    FEATURED_CLEANERS: 'Featured Cleaners',
    WHY_CHOOSE_US: 'Why Choose CleanerCircle',
    HOW_IT_WORKS: 'How It Works',
    TESTIMONIALS: 'What Our Customers Say',
    CTA_TITLE: 'Ready to Find Your Perfect Cleaner?',
    CTA_SUBTITLE: 'Join thousands of Canadians who trust CleanerCircle for their cleaning needs.',
    CTA_BUTTON: 'Get Started Free',
    WHY_ITEMS: {
      VERIFIED: { TITLE: 'Verified Professionals', DESC: 'Every cleaner is background-checked and verified for your peace of mind.' },
      INSURED: { TITLE: 'Fully Insured', DESC: 'All services are covered by comprehensive insurance protection.' },
      RATED: { TITLE: 'Top Rated', DESC: 'Browse real reviews from verified customers across Canada.' },
      SUPPORT: { TITLE: '24/7 Support', DESC: 'Our dedicated support team is always here to help you.' },
    },
    STEPS: {
      SEARCH: { TITLE: 'Search', DESC: 'Browse cleaners and services in your area.' },
      COMPARE: { TITLE: 'Compare', DESC: 'Review profiles, ratings, and pricing.' },
      BOOK: { TITLE: 'Book', DESC: 'Send an enquiry and connect directly.' },
      ENJOY: { TITLE: 'Enjoy', DESC: 'Relax while professionals handle the cleaning.' },
    },
  },

  SEARCH: {
    TITLE: 'Find Cleaning Services',
    SUBTITLE: 'Browse and filter professional cleaning services across Canada',
    SEARCH_PLACEHOLDER: 'Search services, cleaners, or locations...',
    NO_RESULTS: 'No services match your criteria',
    FILTERS: 'Filters',
    CATEGORY: 'Category',
    PRICE_RANGE: 'Price Range',
    MIN_RATING: 'Minimum Rating',
    AVAILABILITY: 'Availability',
    LOCATION: 'Location',
    CLEAR_FILTERS: 'Clear All Filters',
    AVAILABLE_NOW: 'Available Now',
    AVAILABLE_WEEK: 'Available This Week',
    ANY_TIME: 'Any Time',
  },

  SERVICE_DETAILS: {
    ABOUT: 'About This Service',
    FEATURES: 'What\'s Included',
    CLEANER_INFO: 'About the Cleaner',
    RELATED: 'Related Services',
    REVIEWS: 'Customer Reviews',
    PRICE: 'Starting Price',
    DURATION: 'Duration',
    BOOK_SERVICE: 'Book This Service',
    CONTACT_CLEANER: 'Contact Cleaner',
  },

  CLEANER_PROFILE: {
    ABOUT: 'About',
    SERVICES: 'Services Offered',
    REVIEWS: 'Reviews',
    GALLERY: 'Gallery',
    WORKING_HOURS: 'Working Hours',
    EXPERIENCE: 'Experience',
    CERTIFICATES: 'Certificates',
    SEND_ENQUIRY: 'Send Enquiry',
    START_CHAT: 'Start Chat',
    VERIFIED: 'Verified Cleaner',
    MEMBER_SINCE: 'Member since',
    JOBS_COMPLETED: 'Jobs Completed',
    RESPONSE_TIME: 'Response Time',
  },

  LOGIN: {
    TITLE: 'Welcome Back',
    SUBTITLE: 'Sign in to your CleanerCircle account',
    EMAIL: 'Email Address',
    EMAIL_PLACEHOLDER: 'Enter your email',
    PASSWORD: 'Password',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    REMEMBER: 'Remember me',
    FORGOT: 'Forgot password?',
    SUBMIT: 'Sign In',
    GOOGLE: 'Continue with Google',
    NO_ACCOUNT: 'Don\'t have an account?',
    REGISTER: 'Sign up',
    DEMO_HINT: 'Use demo accounts: customer@demo.com, cleaner@demo.com, admin@demo.com (password: demo1234)',
  },

  REGISTER: {
    TITLE: 'Create Your Account',
    SUBTITLE: 'Join CleanerCircle and connect with trusted cleaners',
    SELECT_ROLE: 'I am a...',
    CUSTOMER: 'Customer',
    CUSTOMER_DESC: 'Looking for cleaning services',
    CLEANER: 'Cleaner / Business',
    CLEANER_DESC: 'Offering cleaning services',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    EMAIL: 'Email Address',
    PHONE: 'Phone Number',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    BUSINESS_NAME: 'Business Name',
    SUBMIT: 'Create Account',
    HAVE_ACCOUNT: 'Already have an account?',
    LOGIN: 'Sign in',
    TERMS: 'By creating an account, you agree to our Terms of Service and Privacy Policy.',
  },

  CUSTOMER: {
    DASHBOARD: {
      TITLE: 'Welcome back',
      RECENT_ENQUIRIES: 'Recent Enquiries',
      RECENT_CHATS: 'Recent Messages',
      FAVORITE_CLEANERS: 'Favorite Cleaners',
      STATS: {
        ENQUIRIES: 'Total Enquiries',
        ACTIVE: 'Active Chats',
        FAVORITES: 'Saved Cleaners',
        COMPLETED: 'Completed Jobs',
      },
    },
    ENQUIRIES: {
      TITLE: 'My Enquiries',
      SUBTITLE: 'Track and manage your service enquiries',
      EMPTY: 'You haven\'t sent any enquiries yet.',
      BROWSE: 'Browse Services',
    },
    MESSAGES: {
      TITLE: 'Messages',
      SUBTITLE: 'Chat with cleaners about your enquiries',
      EMPTY: 'No conversations yet.',
      TYPE_MESSAGE: 'Type a message...',
      SEND: 'Send',
      ONLINE: 'Online',
      OFFLINE: 'Offline',
    },
    FAVORITES: {
      TITLE: 'Favorite Cleaners',
      SUBTITLE: 'Your saved cleaners for quick access',
      EMPTY: 'You haven\'t saved any cleaners yet.',
    },
    PROFILE: {
      TITLE: 'My Profile',
      PERSONAL_INFO: 'Personal Information',
      ADDRESSES: 'Saved Addresses',
      SETTINGS: 'Settings',
      NOTIFICATIONS: 'Email Notifications',
      SMS: 'SMS Notifications',
    },
  },

  CLEANER: {
    DASHBOARD: {
      TITLE: 'Cleaner Dashboard',
      STATS: {
        ENQUIRIES: 'New Enquiries',
        ACTIVE: 'Active Jobs',
        RATING: 'Average Rating',
        REVENUE: 'Est. Revenue',
      },
      RECENT_ENQUIRIES: 'Recent Enquiries',
      RECENT_MESSAGES: 'Recent Messages',
      RECENT_REVIEWS: 'Recent Reviews',
    },
    SERVICES: {
      TITLE: 'My Services',
      SUBTITLE: 'Manage your service listings',
      ADD: 'Add Service',
      EDIT: 'Edit Service',
      DELETE: 'Delete Service',
      EMPTY: 'You haven\'t added any services yet.',
      CONFIRM_DELETE: 'Are you sure you want to delete this service?',
    },
    ENQUIRIES: {
      TITLE: 'Incoming Enquiries',
      SUBTITLE: 'Manage customer enquiries',
      ACCEPT: 'Accept',
      REJECT: 'Reject',
      COMPLETE: 'Mark Complete',
      EMPTY: 'No enquiries yet.',
    },
    MESSAGES: {
      TITLE: 'Messages',
      SUBTITLE: 'Communicate with your customers',
    },
    PROFILE: {
      TITLE: 'Business Profile',
      COMPANY: 'Company Details',
      GALLERY: 'Photo Gallery',
      CERTIFICATES: 'Certificates & Licenses',
      HOURS: 'Working Hours',
    },
    REVIEWS: {
      TITLE: 'Customer Reviews',
      SUBTITLE: 'See what customers are saying',
      ANALYTICS: 'Rating Analytics',
      EMPTY: 'No reviews yet.',
    },
  },

  ADMIN: {
    DASHBOARD: {
      TITLE: 'Admin Dashboard',
      OVERVIEW: 'Platform Overview',
      STATS: {
        USERS: 'Total Users',
        CLEANERS: 'Active Cleaners',
        SERVICES: 'Total Services',
        ENQUIRIES: 'Total Enquiries',
      },
    },
    USERS: {
      TITLE: 'Manage Users',
      SUBTITLE: 'View and manage platform users',
    },
    SERVICES: {
      TITLE: 'Manage Services',
      SUBTITLE: 'Review and manage service listings',
    },
    REPORTS: {
      TITLE: 'Reports & Analytics',
      SUBTITLE: 'Platform performance and insights',
    },
  },

  ENQUIRY: {
    MODAL_TITLE: 'Send Enquiry',
    SERVICE: 'Service',
    DATE: 'Preferred Date',
    TIME: 'Preferred Time',
    MESSAGE: 'Message',
    MESSAGE_PLACEHOLDER: 'Tell the cleaner about your requirements...',
    SUBMIT: 'Send Enquiry',
    SUCCESS: 'Enquiry sent successfully!',
    STATUS: {
      PENDING: 'Pending',
      ACCEPTED: 'Accepted',
      COMPLETED: 'Completed',
      CANCELLED: 'Cancelled',
      REJECTED: 'Rejected',
    },
  },

  FOOTER: {
    TAGLINE: 'Canada\'s Trusted Cleaning Marketplace',
    DESCRIPTION: 'Connecting Canadians with trusted cleaning professionals since 2024.',
    QUICK_LINKS: 'Quick Links',
    FOR_CLEANERS: 'For Cleaners',
    SUPPORT: 'Support',
    LEGAL: 'Legal',
    COPYRIGHT: '© 2024 CleanerCircle. All rights reserved.',
    LINKS: {
      ABOUT: 'About Us',
      HOW_IT_WORKS: 'How It Works',
      CAREERS: 'Careers',
      BLOG: 'Blog',
      JOIN: 'Join as Cleaner',
      PRICING: 'Pricing',
      RESOURCES: 'Resources',
      HELP: 'Help Center',
      CONTACT: 'Contact Us',
      FAQ: 'FAQ',
      TERMS: 'Terms of Service',
      PRIVACY: 'Privacy Policy',
      COOKIES: 'Cookie Policy',
    },
  },

  AUTH: {
    LOGOUT_SUCCESS: 'You have been logged out.',
    LOGIN_SUCCESS: 'Welcome back!',
    REGISTER_SUCCESS: 'Account created successfully!',
    INVALID_CREDENTIALS: 'Invalid email or password.',
    SESSION_EXPIRED: 'Your session has expired. Please log in again.',
  },

  TOAST: {
    SUCCESS: 'Success',
    ERROR: 'Error',
    WARNING: 'Warning',
    INFO: 'Info',
    FAVORITE_ADDED: 'Added to favorites',
    FAVORITE_REMOVED: 'Removed from favorites',
    ENQUIRY_SENT: 'Enquiry sent successfully',
    SERVICE_DELETED: 'Service deleted',
    SERVICE_SAVED: 'Service saved',
    COPIED: 'Copied to clipboard',
  },

  EMPTY: {
    ENQUIRIES: 'No enquiries found',
    MESSAGES: 'No messages yet',
    FAVORITES: 'No favorites yet',
    SERVICES: 'No services found',
    REVIEWS: 'No reviews yet',
    USERS: 'No users found',
    NOTIFICATIONS: 'No notifications',
  },
} as const;
